In [1]:
%matplotlib inline

http://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html#sphx-glr-beginner-blitz-tensor-tutorial-py

What is PyTorch?
================

It’s a Python based scientific computing package targeted at two sets of audiences:

-  A replacement for numpy to use the power of GPUs
-  a deep learning research platform that provides maximum flexibility and speed

Getting Started
---------------

Tensors
--------

Tensors are similar to numpy’s ndarrays, with the addition being that Tensors can also be used on a GPU to accelerate computing.


In [2]:
from __future__ import print_function
import torch

Construct a 5x3 matrix, uninitialized:



In [3]:
x = torch.Tensor(5, 3)
print(x)


 0.0000e+00  0.0000e+00  9.5618e-04
 4.5723e-41  8.1394e-23  4.5723e-41
 2.0578e+15  3.0690e-41  2.0578e+15
 3.0690e-41  0.0000e+00  0.0000e+00
 0.0000e+00  0.0000e+00  0.0000e+00
[torch.FloatTensor of size 5x3]



Construct a randomly initialized matrix



In [4]:
x = torch.rand(5, 3) # http://pytorch.org/docs/master/torch.html#torch.rand
print(x)


 0.9864  0.6980  0.6025
 0.3162  0.7554  0.0469
 0.5672  0.2479  0.7876
 0.3677  0.7629  0.5115
 0.3285  0.2588  0.8024
[torch.FloatTensor of size 5x3]



Get its size



In [5]:
print(x.size()) # http://pytorch.org/docs/master/tensors.html#torch.Tensor.size

torch.Size([5, 3])


<div class="alert alert-info"><h4>Note</h4><p>``torch.Size`` is in fact a tuple, so it supports the same operations</p></div>

Operations
-----------
There are multiple syntaxes for operations. Let's see addition as an example

Addition: syntax 1



In [6]:
y = torch.rand(5, 3)
print(y)
print(x + y)


 0.9599  0.8519  0.1933
 0.9885  0.9576  0.5145
 0.6181  0.3924  0.3198
 0.0259  0.5427  0.3005
 0.5339  0.4049  0.2320
[torch.FloatTensor of size 5x3]


 1.9463  1.5499  0.7957
 1.3047  1.7130  0.5614
 1.1853  0.6403  1.1075
 0.3936  1.3056  0.8120
 0.8624  0.6637  1.0343
[torch.FloatTensor of size 5x3]



Addition: syntax 2



In [7]:
print(torch.add(x, y))


 1.9463  1.5499  0.7957
 1.3047  1.7130  0.5614
 1.1853  0.6403  1.1075
 0.3936  1.3056  0.8120
 0.8624  0.6637  1.0343
[torch.FloatTensor of size 5x3]



Addition: giving an output tensor



In [8]:
result = torch.Tensor(5, 3)
torch.add(x, y, out=result)
print(result)


 1.9463  1.5499  0.7957
 1.3047  1.7130  0.5614
 1.1853  0.6403  1.1075
 0.3936  1.3056  0.8120
 0.8624  0.6637  1.0343
[torch.FloatTensor of size 5x3]



Addition: in-place



In [9]:
# adds x to y
y.add_(x)
print(y)


 1.9463  1.5499  0.7957
 1.3047  1.7130  0.5614
 1.1853  0.6403  1.1075
 0.3936  1.3056  0.8120
 0.8624  0.6637  1.0343
[torch.FloatTensor of size 5x3]



<div class="alert alert-info"><h4>Note</h4><p>Any operation that mutates a tensor in-place is post-fixed with an ``_``
    For example: ``x.copy_(y)``, ``x.t_()``, will change ``x``.</p></div>

You can use standard numpy-like indexing with all bells and whistles!



In [10]:
print(x[:, 1]) # all rows of 2nd column


 0.6980
 0.7554
 0.2479
 0.7629
 0.2588
[torch.FloatTensor of size 5]



**Read later:**


  100+ Tensor operations, including transposing, indexing, slicing,
  mathematical operations, linear algebra, random numbers, etc are described
  `here <http://pytorch.org/docs/torch>`_

Numpy Bridge
------------

Converting a torch Tensor to a numpy array and vice versa is a breeze.

The torch Tensor and numpy array will share their underlying memory
locations, and changing one will change the other.

Converting torch Tensor to numpy Array
------------------------------------------

In [11]:
a = torch.ones(5)
print(a)


 1
 1
 1
 1
 1
[torch.FloatTensor of size 5]



In [12]:
b = a.numpy() # http://pytorch.org/docs/master/tensors.html#torch.Tensor.numpy
print(b)

[ 1.  1.  1.  1.  1.]


See how the numpy array changed in value.



In [13]:
a.add_(1) # http://pytorch.org/docs/master/tensors.html#torch.Tensor.add_
print(a)
print(b)


 2
 2
 2
 2
 2
[torch.FloatTensor of size 5]

[ 2.  2.  2.  2.  2.]


Converting numpy Array to torch Tensor
------------------------------------------
See how changing the np array changed the torch Tensor automatically

In [14]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a) # http://pytorch.org/docs/master/torch.html#torch.from_numpy
np.add(a, 1, out=a)
print(a)
print(b)

[ 2.  2.  2.  2.  2.]

 2
 2
 2
 2
 2
[torch.DoubleTensor of size 5]



All the Tensors on the CPU except a CharTensor support converting to
NumPy and back.

CUDA Tensors
------------

Tensors can be moved onto GPU using the ``.cuda`` function.



In [15]:
# let us run this cell only if CUDA is available
if torch.cuda.is_available():
    x = x.cuda()
    y = y.cuda()
    x + y
    print("CUDA is available")

In [16]:
torch.cuda.is_available()

False